apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: color-rollout
  namespace: argo-rollouts
spec:
  replicas: 1
  strategy:
    canary:
      canaryService: color-canary
      stableService: color-stable
      trafficRouting:
        plugins:
          argoproj-labs/gatewayAPI:
            httpRoute: color-route # our created httproute
            namespace: argo-rollouts
      steps:
        - setWeight: 30
        - pause: { duration: 15 }
        - setWeight: 40
        - pause: { duration: 15 }
        - setWeight: 60
        - pause: { duration: 15 }
        - setWeight: 80
        - pause: { duration: 15 }
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      service: color
  template:
    metadata:
      labels:
        service: color
    spec:
      containers:
      - name: color
        image: dwflynn/faces-service:0.8.0
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: FACES_SERVICE
          value: "color"
        - name: COLOR
          value: "green"
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 1
          periodSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi