---
apiVersion: v1
kind: Service
metadata:
  name: color-canary
  namespace: argo-rollouts
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    service: color
---
apiVersion: v1
kind: Service
metadata:
  name: color-stable
  namespace: faces
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    service: color
